# Generated by Django 3.2.3 on 2021-05-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmodel',
            name='years',
            field=models.IntegerField(default=0, verbose_name='経験年数'),
        ),
    ]
